version: '3.7'
services: 
    etl:
        restart: always
        image: etl:01
        build: ./ethereum-etl
        command: stream --provider-uri="https://mainnet.infura.io/v3/6a3f7fe0b96044b5ae8a3cbaf22920c3" --block-batch-size=10000 --batch-size=100 --max-workers=100 --last-synced-block-file="last_synced_block_c.txt"  --output="postgresql+pg8000://postgres:root@127.0.0.1:5432/ethereumetl"
        volumes:
        - ./ethereum-etl:/ethereum-etl
        - logvolumeetl01:/var/log
        network_mode: "host"
volumes:
    logvolumeetl01:
