version: '3.7'
services: 
    etl:
        restart: always
        image: etl:01
        build: ./ethereum-etl
        command: stream --provider-uri=${provider_uri} --block-batch-size=${block_batch_size} --batch-size=${batch_size} --max-workers=100 --last-synced-block-file=${last_synced_block_file}  --output="postgresql+pg8000://${db_user}:${db_pass}@${db_host}:${db_port}/${db_name}"
        volumes:
        - ./ethereum-etl:/ethereum-etl
        - logvolumeetl01:/var/log
        network_mode: "host"
volumes:
    logvolumeetl01:
